CREATE VIEW "DBA"."vAktualneRezerwacje"()
AS
SELECT R.ID_R,
       G.IMIE ||' '|| G.NAZWISKO AS 'Imie i nazwisko gościa',
       P.IMIE ||' '|| P.NAZWISKO AS 'Imie i nazwisko pracownika',
       G.TELEFON AS TELEFON_GOSCIA,
       R.NR_POKOJU,
       PO.LICZBA_MIEJSC,
       KP.NAZWA_KLASY,
       R.DATA_OD,
       R.DATA_DO
FROM REZERWACJA R
     INNER JOIN GOSC G ON G.PESEL_G=R.PESEL_G
     INNER JOIN PRACOWNIK P ON P.PESEL_P=R.PESEL_P
     INNER JOIN POKOJ PO ON PO.NR_POKOJU=R.NR_POKOJU
     INNER JOIN KLASA_POKOJU KP ON KP.ID_KP=PO.ID_KP
WHERE R.DATA_OD < now() AND R.DATA_DO >=now();



CREATE MATERIALIZED VIEW "DBA"."vmRezerwacjeOplaconeKarta"()
IN "system" AS
SELECT R.ID_R,
       G.IMIE ||' '|| G.NAZWISKO AS 'Imie i nazwisko gościa',
       P.IMIE ||' '|| P.NAZWISKO AS 'Imie i nazwisko pracownika',
       G.TELEFON AS TELEFON_GOSCIA,
       R.NR_POKOJU,
       PL.SPOSOB_PLATNOSCI,
       PL.CZY_FAKTURA,
       PL.NIP,
       K.NR_KARTY,
       R.KWOTA,
       PL.DATA_PLATNOSCI
FROM REZERWACJA R
     INNER JOIN GOSC G ON G.PESEL_G=R.PESEL_G
     INNER JOIN PLATNOSC PL ON PL.ID_R=R.ID_R
     INNER JOIN KARTA K ON K.PESEL_G=G.PESEL_G
     INNER JOIN PRACOWNIK P ON P.PESEL_P=R.PESEL_P
WHERE PL.SPOSOB_PLATNOSCI='KARTA'
ORDER BY R.KWOTA DESC;

CREATE VIEW "DBA"."vPracownicyZprawoJazdyB"()
AS
SELECT P.IMIE,
       P.NAZWISKO, 
       P.TELEFON,
       P.STANOWISKO,
       K.NAZWA_KWALIFIKACJI
FROM PRACOWNIK P
     INNER JOIN KWALIFIKACJE_PRACOWNIKA KP ON KP.PESEL_P=P.PESEL_P
     INNER JOIN KWALIFIKACJE K ON K.ID_K=KP.ID_K
WHERE K.ID_K=1
ORDER BY P.STANOWISKO DESC;